---
- name: "Ensure {{ remote_dest }} directory exists"
  win_file:
    path: "{{ remote_dest }}"
    state: directory

- name: "Upload SAP Crystal Reports {{ crystal_rpt_exe }} binary"
  win_copy:
    src: "{{ local_src }}/{{ crystal_rpt_exe }}.zip"
    dest: "{{ remote_dest }}\\{{ crystal_rpt_exe }}.zip"
    remote_src: False
  register: crystal_reports_binary

- name: Create a {{ response_file }} 
  win_template:
    src: "{{ response_file }}.j2"
    dest: "{{ remote_dest }}\\{{ response_file }}"

- name: "Unzip {{ crystal_rpt_exe }}.zip repo to {{ remote_dest }}" 
  win_unzip:
    src: "{{ remote_dest }}\\{{ crystal_rpt_exe }}.zip"
    dest: "{{ remote_dest }}"
    creates: "{{ remote_dest }}\\{{ crystal_rpt_exe }}"
  when: crystal_reports_binary

- name: Install SAP Crystal Reports
  win_package:
    path: "{{ remote_dest }}\\{{ crystal_rpt_exe }}\\setup.exe" 
    product_id: '{018ECF3F-26EA-4969-9FCC-810893F9C2DE}'
    arguments: "-r {{ remote_dest }}\\{{ response_file }}"
  register: crystal_reports_installed
  when: crystal_reports_binary
